add_newline = true
palette = "catppuccin_mocha"

format = """
[╭─](green)\
$os\
$directory\
$nix_shell\
$python\
$nodejs\
$rust\
$golang\
$git_branch\
$git_status\
$line_break\
$character"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bold sapphire"
format = "[$symbol]($style)"

[os.symbols]
NixOS = " "
Windows = " "
Ubuntu = " "
Macos = " "
Linux = " "
Arch = " "

[directory]
style = "bold blue"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[python]
style = "bold lavender"
symbol = " "
format = '[ via ](overlay0)[${symbol}${version}]($style)'
version_format = "v${raw}"

[nix_shell]
symbol = " "
style = "bold sapphire"
format = '[ via ](overlay0)[$symbol$state]($style)'
impure_msg = "(impure)"
pure_msg = "(pure)"

[nodejs]
style = "bold green"
format = '[ via ](overlay0)[${symbol}${version}]($style)'
symbol = " "

[rust]
style = "bold red"
format = '[ via ](overlay0)[${symbol}${version}]($style)'
symbol = " "

[git_branch]
symbol = " "
style = "mauve"
format = '[ on ](overlay0)[$symbol$branch]($style)'

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style))'

[character]
success_symbol = "[╰─](bold green)"
error_symbol = "[╰─](bold red)"
vimcmd_symbol = "[╰─ ❮](green)"
