theme = "catppuccin_mocha"
[editor]
color-modes = true
cursorline = true
line-number = "relative"
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
y = ["yank", ":clipboard-yank"]
p = ":clipboard-paste-before"
P = ":clipboard-paste-after"

[keys.select]
y = ["yank", ":clipboard-yank"]
p = ":clipboard-paste-before"
P = ":clipboard-paste-after"

[keys.normal.space]
q = ":q"
space = "file_picker"
w = ":w"

