theme = "catppuccin_mocha"
[editor]
color-modes = true
cursorline = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
y = ["yank", ":clipboard-yank"]
p = ":clipboard-paste-before"
P = ":clipboard-paste-after"

[keys.select]
y = ["yank", ":clipboard-yank"]
p = ":clipboard-paste-before"
P = ":clipboard-paste-after"

[keys.normal.space]
q = ":q"
space = "file_picker"
w = ":w"
